- docs/dev_docs/merger.md
- docs/user_docs/merger_usage.md
- src/main_test.go
Please have a look to ensure whether we have the same understanding of the merger :)
> Docs: User and dev doc for basic merger

- docs/dev_docs/fetcher.md
- docs/user_docs/fetcher_usage.md
This was missing from the fetcher
> docs: add fetcher documentation

- docs/dev_docs/fetcher.md
- src/Fetcher/fetcher.go
- src/Fetcher/fetcher_test.go
- src/Merger/merger.go
- src/Verifier/verifier.go
- src/Verifier/verifier_test.go
- src/cmd/fetch.go
- src/specfile.txt
- test/end2end_test.go
This PR refactors the fetcher to use go funcs making it run asynchronously. This greatly speeds up the fetching process when fetching from multiple repos
Resolves [#77](https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/1?pane=issue&itemId=59319657)
> refactor: async fetcher

- LICENSE
See title
Resolves [#97](https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/1?filterQuery=lice&pane=issue&itemId=60029331)
> chore: Change LICENSE to GAGPL 3.0

- README.md
See title
Resolves [#110](https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/3?pane=issue&itemId=60910495)
> chore: add credit to thoughtworks in readme

- src/Fetcher/fetcher.go
See title
Resolves [#105](https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/1?filterQuery=standa&pane=issue&itemId=60840450)
> refactor: progres bar now rounds to nearest 5% and is always 20 long

- docs/user_docs/fetcher_usage.md
- src/cmd/fetch.go
- src/repos.txt
- test/end2end_test.go
- test/integration_test.go
This PR lets the user use the repo-file flag to specify a file containing links to repo as well as branch and whitelist file information. This can be simplified by combining it with the branch and whitelist flags.
Resolves [#37](https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/3?pane=issue&itemId=56771516)
> feat: file of repos for fetching

- .github/dependabot.yml
Resolves https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/1?pane=issue&itemId=61265987
> ci: update dependabot to now include gomod

- docs/dev_docs/merger.md
- src/Merger/merger.go
- src/Merger/merger_test.go
Resolves ... [#124](https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/3?pane=issue&itemId=61118341)
Note that the only change in Merger's doc is saying ReadCsvFile() calls scanFile(), and describing scanFile().
> test: Add test for Merger's duplicationRemoval

- src/Merger/merger.go
- src/Verifier/verifier.go
This PR has a few comments for the Regex and duplicate removal functions that are unreadable
Resolves https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/7?pane=issue&itemId=61288458
> docs: add comments to funky code

- src/HTML/js/renderingTechRadar.js
resolve [#103](https://github.com/NovoNordisk-OpenSource/decentralized-tech-radar/issues/103)
> bug: make quadrant names show

- .golangci.yml
See title
Resolves https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/7?pane=issue&itemId=61364156
> chore: add a go linter yaml file

- docs/dev_docs/fetcher.md
- src/Fetcher/fetcher.go
- src/Fetcher/fetcher_test.go
See title
Resolves https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/3?pane=issue&itemId=61294683
> feat: add url to fetched files

- docs/user_docs/remove_usage.md
- src/cmd/remove.go
- test/end2end_test.go
...  from tech radar specification file
Resolves. [#136](https://github.com/NovoNordisk-OpenSource/decentralized-tech-radar/issues/136)
> feat: CLI can facilitate removing elements

- Makefile
see title 
Resolves [#145](https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/3?pane=issue&itemId=61604811)
> chore: add a makefile to build project

- .github/workflows/build_test_release.yml
see title
Resolves [#146](https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/3?pane=issue&itemId=61666156)
> ci: fix file extension for windows binary

- src/Merger/Fcfs.go
> fix: fix issue where merge log didn't show picked file

- src/HTML/css/style.css
- src/HTML/js/renderingTechRadar.js
- src/HTML/makeHtml.go
This resolves the rendering not happening during releases, due to wrong filepath for html and css.
> fix: rendering path for both html and css

- .github/workflows/radar_workflow.yml
- ci/radar_build.go
- examples/workflows/ci/radar_build.go
- examples/workflows/github/radar_workflow.yml
- examples/workflows/workflows.md
This PR contains an example workflow to generate a tech radar html file using a git tag `make_radar-v*` 
Resolves [#148](https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/3?pane=issue&itemId=62170065)
> ci: workflow example to generate radar

- src/SpecReader/specReader.go
- src/SpecReader/specReader_test.go
Removes the structs and the unused function from the SpecReader
Resolves: [#178](https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/3?pane=issue&itemId=62392130)
> refactor: remove unused code
